"""add votes table

Revision ID: 37bbab162c42
Revises: 2a2cc3fc3fe7
Create Date: 2026-09-21 17:21:58.905189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37bbab162c42'
down_revision: Union[str, Sequence[str], None] = '2a2cc3fc3fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('value IN (-1, 1)', name='ck_votes_value'),
    # sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    # autogenerate does not emit ondelete; added by hand. Required because the
    # ORM relationships use passive_deletes=True, i.e. they expect the database
    # to cascade. Without it, deleting a post or user that has votes fails with
    # ForeignKeyViolation.
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_votes_user_post')
    )
    op.create_index(op.f('ix_votes_id'), 'votes', ['id'], unique=False)
    op.create_index(op.f('ix_votes_post_id'), 'votes', ['post_id'], unique=False)
    op.drop_column('posts', 'likes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('likes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_votes_post_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_id'), table_name='votes')
    op.drop_table('votes')
    # ### end Alembic commands ###
